module1-task2 проверка 1
htmlacademy-ecmascript/1679727-cinemaddict-15 pull request #3
Opened 2021-08-03 11:00 UTC by talexden

Есть ощущение, что "немного" перемудрил :)

2021-08-04 18:56 UTC, ademaro commented on src/index.js
> +export * from './utils';
а про index.js — вам на лекции рассказывали?

2021-08-04 19:01 UTC, ademaro commented on src/main.js
> +renderPopup();
Совсем вкратце — в main.js должно быть:
1. Импорт ф-ций для создания моков и собственно их генерация
2. Импорт шаблонов и их рендер (с передачей данных, которые намокали до этого)

У нас сейчас две функции, которые сильно скрывают реализацию и не совсем понятно и очевидно рендрят два куска) В общем предлагаю созвониться и обсудить подробнее, что бы мы не ушли совсем в сторону

2021-08-04 19:03 UTC, ademaro commented on src/renders/render-page.js
> +import {main} from '../';
ну это совсем не очевидно откуда ты что импортируешь, причём разбиваешь на три импорта. В общем вопросов пока больше чем ответов) Давай активно побуждаем твою логику

2021-08-04 19:06 UTC, ademaro requested changes
Надо разобрать этот хаос, ты вряд ли сможешь адекватно работать с таким кодом, ПР пока оставляю открытым, нужны правки. С утра буду на связи, если что.

2021-08-04 19:33 UTC, talexden commented on src/index.js
> +export * from './utils';
ну, в подготовке к лекции про проксирование и пути рассказали часть, тема заинтересовала, почитал статьи, нашел в них информацию про файл по умолчанию (index.js). не помню уже где даже и вычитал. Это своего рода эксперимент, сработает ли такая конструкция, пока вроде работает. Я вроде логически подумал, если не делать петель (а их не будет, если импортировать только из рут каталога) - то все нормально будет.
Теряется информативность из какого блока импортирована функция, но современные IDE - отслеживают пути и с удовольствием рисуют карты зависимостей...
от себя помимо курса добавлена только index.js  и немного логических размышлений.
Готов к критике )

2021-08-04 19:36 UTC, talexden commented on src/renders/render-page.js
> +import {main} from '../';
три импорта, константы, функции, постоянные пути (те, которые не нужно искать по 100 раз, когда страница сформирована).

2021-08-04 19:45 UTC, talexden commented on src/renders/render-page.js
> +import {main} from '../';
можно было и одним, но мне показалось, что 3-мя понятней будет.

2021-08-04 19:48 UTC, talexden commented on src/main.js
> +renderPopup();
посмотрел 2-й лайв, стало немного понятней, для чего мы это все разбивали.
Теперь я бы разбил шаблоны на "статику" и "динамику".
в "статике" отрисовал все элементы и блоки, количество которых известно заранее. отрисовал в 2  шаблона:  онсновная страница и попап.
в "динамику" - все, где меняются данные, это карточки, информация в попапе, комментарии. все, у чего количетво элементов на странице - зависит от приходящих с сервера данных.

2021-08-04 19:49 UTC, talexden commented on src/main.js
> +renderPopup();
готов созвониться, обсудить.

2021-08-04 19:49 UTC, talexden commented on src/main.js
> +renderPopup();
готов все переписать 
как надо :)

2021-08-05 04:33 UTC, ademaro approved these changes

2021-08-05 04:33 UTC, merged